backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'employee'
    label: 'Employee'
    folder: 'src/pages/contact'
    create: true
    identifier_field: name
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'employee',
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Picture', name: 'picture', widget: image }
      - { label: 'Phone Number', name: 'phonenumber', widget: 'number' }
      - { label: 'E-mail', name: 'email', widget: 'string' }
      - { label: 'LinkedIn', name: 'linkedin', widget: 'string' }
  - name: 'productcategory'
    label: 'Product Categories'
    folder: 'src/pages/productCategory'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'productcategory',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Text', name: 'text', widget: 'markdown' }
  - name: 'product'
    label: 'Products'
    folder: 'src/pages/product'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'product',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
      - { label: 'Header Image', name: 'headerimage', widget: image }
      - { label: 'Description 1', name: 'description1', widget: 'markdown' }
      - { label: 'Infobox 1', name: 'infobox1', widget: 'markdown' }
      - {
          label: Product Brochures,
          name: productbrochures,
          widget: list,
          fields:
            [
              { label: Title, name: title, widget: string, pattern: ['.{1,30}', "There is a maximum limit of 30 characters"] },
              { label: File, name: file, widget: customfiles },
            ],
        }
      - { label: 'Small Image', name: 'smallimage', widget: image }
      - { label: 'Fullwidth Image', name: 'fullwidthimage', widget: image }
      - { label: 'Description 2', name: 'description2', widget: 'markdown' }
      - { label: 'Infobox 2', name: 'infobox2', widget: 'markdown' }
      - {
          label: 'Product Category',
          name: 'productcategory',
          widget: 'relation',
          collection: 'productcategory',
          searchFields: 'title',
          valueField: 'title',
        }
  - name: 'project'
    label: 'Projects'
    folder: 'src/pages/project'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Main Image', name: 'mainimage', widget: image }
      
      - { label: 'Second Title', name: 'title1', widget: 'string' }
      - {
          label: 'Second Description',
          name: 'description1',
          widget: 'markdown',
        }
      - { label: 'First Miniature Image', name: 'miniatureimage1', widget: image }
      - { label: 'Second Miniature Image', name: 'miniatureimage2', widget: image }
      - { label: 'Third Title', name: 'title2', widget: 'string' }
      - { label: 'Third Description', name: 'description2', widget: 'markdown' }
      - {
        label: 'Related Products',
        name: 'relatedproducts',
        widget: 'object',
        fields:
          [
            {
              label: 'Related Product 1',
              name: 'relatedproduct1',
              widget: 'relatedProduct',
              collection: 'product',
              searchFields: 'title',
              valueField: 'title',
              displayFields: 'title',
              required: false
            },
            {
              label: 'Related Product 2',
              name: 'relatedproduct2',
              widget: 'relatedProduct',
              collection: 'product',
              searchFields: 'title',
              valueField: 'title',
              displayFields: 'title',
              required: false
            },
            {
              label: 'Related Product 3',
              name: 'relatedproduct3',
              widget: 'relatedProduct',
              collection: 'product',
              searchFields: 'title',
              valueField: 'title',
              displayFields: 'title',
              required: false
            },
          ],
        }
      - {
        label: 'Category',
        name: 'category',
        widget: 'select',
        required: true,
        options:
          [
              'FishSludge Recovery System', 
              'Protein Recycling',
              'Oil & Gas',
              'Co2 Capture'
          ],
      }
  - name: 'blog'
    label: 'Recent updates'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date', format: "DD.MM.YYYY" }
      - { label: 'Image', name: 'featuredimage', widget: image }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { 
          label: "Social Media", 
          name: "socialmedia", 
          widget: "select", 
          options: ["Instagram", "LinkedIn", "Facebook"],
          default: ["Instagram"], 
        }  
  - name: 'solution'
    label: 'Solution'
    folder: 'src/pages/solutions'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'solution',
        }
      - { label: 'Header Title', name: 'title', widget: 'string' }
      - { label: 'Header Byline', name: 'subtitle', widget: 'string' }
      - { label: 'Header Image', name: 'featuredimage', widget: image }
      - { label: 'Main quote', name: 'mainquote', widget: 'text' }
      - { label: 'Description 1', name: 'description1', widget: 'markdown' }
      - { label: 'Infobox 1', name: 'infobox1', widget: 'markdown' }
      - { label: 'Fullwidth Image', name: 'fullwidthimage', widget: image }
      - { label: 'Description 2', name: 'description2', widget: 'markdown' }
      - { label: 'Description 3', name: 'description3', widget: 'markdown' }
      - { label: 'Description background', name: 'descriptionimage', widget: image }
      - {
        label: 'Related Products',
        name: 'relatedproducts',
        widget: 'object',
        fields:
          [
            {
              label: 'Related Product 1',
              name: 'relatedproduct1',
              widget: 'relatedProduct',
              collection: 'product',
              searchFields: 'title',
              valueField: 'title',
              displayFields: 'title',
              required: false
            },
            {
              label: 'Related Product 2',
              name: 'relatedproduct2',
              widget: 'relatedProduct',
              collection: 'product',
              searchFields: 'title',
              valueField: 'title',
              displayFields: 'title',
              required: false
            },
            {
              label: 'Related Product 3',
              name: 'relatedproduct3',
              widget: 'relatedProduct',
              collection: 'product',
              searchFields: 'title',
              valueField: 'title',
              displayFields: 'title',
              required: false
            },
          ],
        }
      - {
          label: 'Solution Category',
          name: 'solutioncategory',
          widget: 'relation',
          collection: 'solutioncategory',
          searchFields: 'title',
          valueField: 'title',
        }
  - name: 'solutioncategory'
    label: 'Solution Categories'
    folder: 'src/pages/solutionCategory'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'solutioncategory',
        }
      - { label: 'Header Image', name: 'featuredimage', widget: image }
      - { label: 'Header Title', name: 'title', widget: 'string' }
      - { label: 'Header byline', name: 'subtitle', widget: 'text' }
      - { label: 'Text title', name: 'texttitle', widget: 'string' }
      - { label: 'Information', name: 'information', widget: 'markdown' }
  - name: 'testcentreentry'
    label: 'Test Centre Entries'
    folder: 'src/pages/test-centre-post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'test-centre-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date', format: "DD.MM.YYYY" }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Text', name: 'text', widget: 'text' }
  
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Ingress', name: 'ingress', widget: 'text' }
          - { label: Image, name: image, widget: image }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/contact/index.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'contact-page',
            }
          - { label: 'Header title', name: 'headertitle', widget: 'string' }
          - { label: 'Header byline', name: 'headerbyline', widget: 'string' }
          - { label: 'Header image', name: 'headerimage', widget: image }
          - { label: 'Form title', name: 'formtitle', widget: 'string' }
          - { label: 'Employee title', name: 'employeetitle', widget: 'string' }
          - { label: 'Address or Place', name: 'mapiframe', widget: 'string' }
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - {
              label: Index image,
              name: indexblock,
              widget: object,
              fields:
                [
                  { label: Title 1, name: title1, widget: string },
                  { label: 'Image 1', name: 'image1', widget: image },
                  { label: Link 1 (Must include http/https), name: link1, widget: string },
                  { label: Title 2, name: title2, widget: string },
                  { label: 'Image 2', name: 'image2', widget: image },
                  { label: Link 2 (Must include http/https), name: link2, widget: string },
                ],
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Middle block,
              name: middleblock,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: 'image2', widget: image }
                ],
            }
          - {
              label: Partners,
              name: partners,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: partnerimage,
                    name: partnerimage,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Link, name: link, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/products/index.md'
        label: 'Products Page'
        name: 'productpage'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'product-categories-page',
            }
          - { label: 'Header title', name: 'headertitle', widget: 'string' }
          - { label: 'Header byline', name: 'headerbyline', widget: 'string' }
          - { label: 'Header image', name: 'headerimage', widget: image }
          - { label: 'Products Quote', name: 'productsquote', widget: 'string' }
      - file: 'src/pages/projects/index.md'
        label: 'Projects Page'
        name: 'projects'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'projects',
            }
          - { label: 'Header title', name: 'headertitle', widget: 'string' }
          - { label: 'Header byline', name: 'headerbyline', widget: 'string' }
          - { label: 'Header image', name: 'headerimage', widget: image }
          - { label: 'Projects Quote', name: 'projectsquote', widget: 'string' }
      - file: 'src/pages/solutions-page/index.md'
        label: 'Solutions Page'
        name: 'solutionspage'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'solution-categories-page',
            }
          - { label: 'Header title', name: 'headertitle', widget: 'string' }
          - { label: 'Header byline', name: 'headerbyline', widget: 'string' }
          - { label: 'Header image', name: 'headerimage', widget: image }
          - { label: 'Solutions Quote', name: 'solutionsquote', widget: 'string' }
      - file: 'src/pages/test-centre-page/index.md'
        label: 'Test Centre Page'
        name: 'testcentre'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'test-centre-page',
            }
          - { label: 'Header title', name: 'headertitle', widget: 'string' }
          - { label: 'Ingress', name: 'ingress', widget: 'text' }
          - {
                    label: Images,
                    name: testcentreimages,
                    widget: object,
                    fields:
                      [
                        { label: Image 1, name: image1, widget: image },
                        { label: Image 2, name: image2, widget: image },
                        { label: Image 3, name: image3, widget: image },
                      ]
            }
          - { label: 'Contact Title', name: 'contacttitle', widget: 'string' }
